version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_JWT_SECRET: ${VITE_JWT_SECRET}
        VITE_OPENAI_API_KEY: ${VITE_OPENAI_API_KEY}
        VITE_PORT: ${VITE_PORT}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "80:4173"
    environment:
      - VITE_JWT_SECRET=${VITE_JWT_SECRET}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_PORT=${VITE_PORT}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - RUNNING_IN_DOCKER=true
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_KEY=${AZURE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    volumes:
      - ./backend:/app
